export default `<!DOCTYPE html><html lang="en" data-beasties-container><head>
  <meta charset="utf-8">
  <title>StreakTracker</title>
  <base href="https://arshadvk18.github.io/streakapp/">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" type="image/x-icon" href="favicon.ico">
<link rel="stylesheet" href="styles-M6CKNAHS.css" media="print" onload="this.media='all'"><noscript><link rel="stylesheet" href="styles-M6CKNAHS.css"></noscript><link rel="preload" href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" as="style"></head>
<body><!--nghm--><script type="text/javascript" id="ng-event-dispatch-contract">(()=>{function p(t,n,r,o,e,i,f,m){return{eventType:t,event:n,targetElement:r,eic:o,timeStamp:e,eia:i,eirp:f,eiack:m}}function u(t){let n=[],r=e=>{n.push(e)};return{c:t,q:n,et:[],etc:[],d:r,h:e=>{r(p(e.type,e,e.target,t,Date.now()))}}}function s(t,n,r){for(let o=0;o<n.length;o++){let e=n[o];(r?t.etc:t.et).push(e),t.c.addEventListener(e,t.h,r)}}function c(t,n,r,o,e=window){let i=u(t);e._ejsas||(e._ejsas={}),e._ejsas[n]=i,s(i,r),s(i,o,!0)}window.__jsaction_bootstrap=c;})();
</script><script>window.__jsaction_bootstrap(document.body,"ng",["input","compositionstart","compositionend","click"],["blur"]);</script>
  <app-root ng-version="19.2.1" ngh="1" ng-server-context="ssg"><app-streak ngh="0"><div class="min-h-screen bg-gray-100 flex flex-col items-center py-10 px-4"><h1 class="text-3xl md:text-4xl font-bold text-green-600 text-center mb-6">Islamic Streak App</h1><div class="bg-white p-6 rounded-lg shadow-lg w-full max-w-md"><h2 class="text-2xl font-semibold text-gray-700 mb-4 text-center">Track Your Islamic Habits</h2><div class="flex flex-col sm:flex-row sm:space-x-2 space-y-2 sm:space-y-0"><input type="text" placeholder="Enter Streak Name" class="w-full px-4 py-2 border rounded-lg focus:ring focus:ring-green-300 ng-untouched ng-pristine ng-valid" value jsaction="input:;blur:;compositionstart:;compositionend:;"><button class="px-4 py-2 bg-green-600 text-white rounded-lg hover:bg-green-700" jsaction="click:;"> Add </button></div></div><div class="mt-6 w-full max-w-md"><ul class="space-y-4"><!----></ul></div></div></app-streak></app-root>
<script src="polyfills-FFHMD2TL.js" type="module"></script><script src="main-IUMDYZVM.js" type="module"></script>

<script id="ng-state" type="application/json">{"__nghData__":[{"t":{"12":"t0"},"c":{"12":[]}},{}]}</script></body></html>`;